export const userActionType = {
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
    REGISTER_LOADING: "REGISTER_LOADING",

    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGIN_LOADING:"LOGIN_LOADING",
    
    LOGOUT: 'USERS_LOGOUT',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE', 
    
    GET_USER_SUCCESS: "GET_USER_SUCESS",
    GET_USER_FAIL: "GET_USER_FAIL",


    QUICK_LOG_POST: "QUICK_LOG_POST",
    QUICK_LOG_POST_FAIL: "QUICK_LOG_POST_FAIL"
};
